version: '3.8'

services:
 #criando o serviço:
    bd: 
  # imagem do container
      image: becafernn/mysql-novascan:latest
  # nome do container
      container_name: bd-novascan
  # variaveis de ambiente
      environment:
        MYSQL_ROOT_PASSWORD=urubu100
  # direcionamento de porta
      ports:
        - "3306:3306"
  # definindo qual rede o serviço vai se comunicar
      networks:
        - rede-novascan
  # volume para persistencia de dados
      

    app:
      image: becafernn/nodejs-novascan:latest
      working_dir: /aplicacao
      ports:
        - "8080:8080"
      volumes:
        - .:/aplicacao
        - /aplicacao/package.json
      environment:
        - NODE_ENV=development
      command: npm start
      networks:
        - rede-novascan
      stdin_open: true


networks:
  rede-novascan:
    driver: bridge
  

  