services:
  # nome do serviço 
    bd: 
  # imagem do container
      image: mysql:5.7
  # nome do container
      container_name: bancoDeDados
  # variaveis de ambiente
      environment:
        MYSQL_ROOT_PASSWORD=urubu100
        MYSQL_DATABASE=bancoTeste
  # direcionamento de porta
      ports:
        - "3306:3306"
  # definindo qual rede o serviço vai se comunicar
      networks:
        - back-end
  # volume para persistencia de dados
      volumes:
        - db_data:/var/lib/mysql

    backend:
      imagem: node:8
      container_name: nodeJs
  # repositorio de inicialização
      working_dir: /app
      volumes:
        - ./app:/app
        - /app/node_modules
  # redirecionamento de porta
      ports:
        - "3000:3000"
  # definindo qual rede o serviço vai se comunicar
      networks:
        - back-end
        - front-end
  # comando que será executado dentro do repositorio de inicialização
      command: npm start

    frontend:
      image: nginx
      ports:
        - "80:80"
    # definindo qual rede o serviço vai se comunicar
      networks:
        - front-end

# definindo o driver a ser utilizado pelas redes (bridge = ponte entre containers (rede padrão))
# existem outras com a Host e None
networks:
  front-end:
    driver: bridge
  back-end:
    driver: bridge

volume:
# definindo um nome para o volume para ser mais facil de identificar
  db_data:
  